name: env_civl575
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11.6
  - jupyter=1.0.0
  - numpy=1.25.2
  - scipy=1.11.1
  - matplotlib=3.7.2
  - ipympl=0.9.3
  - pandas=2.0.3
  - ipywidgets=8.0.4
  - tqdm



